# Generated by Django 3.2.19 on 2024-06-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_price', models.FloatField()),
                ('product_desc', models.TextField()),
                ('product_img', models.ImageField(blank=True, upload_to='static/product_images')),
                ('product_category', models.CharField(choices=[('Clothing', 'Clothing'), ('Footwear', 'Footwear'), ('Accessories', 'Accessories'), ('Jewellery', 'Jewellery'), ('Device Accessories', 'Device Accessories')], max_length=20)),
            ],
        ),
    ]
