# Generated by Django 5.0.6 on 2024-07-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_product',
            name='product_availability',
            field=models.TextField(default='In Stock'),
        ),
        migrations.AddField(
            model_name='new_product',
            name='product_review',
            field=models.IntegerField(default=0),
        ),
    ]
