# Generated by Django 5.0.6 on 2024-07-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_new_product_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_product',
            name='product_availability',
        ),
        migrations.AddField(
            model_name='new_product',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
