# Generated by Django 5.0.6 on 2024-07-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_remove_new_product_product_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.TextField()),
                ('email', models.CharField(max_length=40)),
                ('user_img', models.ImageField(blank=True, upload_to='static/team_images')),
                ('whatsapp', models.CharField(max_length=20)),
                ('instagram', models.TextField()),
                ('twitter', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('user_cover', models.ImageField(blank=True, upload_to='static/team_images')),
            ],
        ),
    ]
