# Generated by Django 5.0.6 on 2024-07-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tasks',
            new_name='New_task',
        ),
        migrations.RenameField(
            model_name='new_task',
            old_name='task',
            new_name='new_task',
        ),
    ]
