# Generated by Django 5.0.6 on 2024-08-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_rename_tasks_new_task_rename_task_new_task_new_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_product',
            name='actual_prod_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='new_product',
            name='discount_price',
            field=models.IntegerField(default=0),
        ),
    ]
