# Generated by Django 5.0.6 on 2024-07-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.TextField(default=''),
        ),
    ]
