# Generated by Django 5.0.6 on 2024-07-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_delivery_order_email_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
