# Generated by Django 5.0.6 on 2024-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='product_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
