# Generated by Django 5.0.6 on 2024-07-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_cartproduct_product_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_total',
            field=models.IntegerField(default=0),
        ),
    ]
